export { useInstances, useInstance, instanceKeys } from '@/hooks/queries/use-instances'
export { useVolumes, useVolume, volumeKeys } from '@/hooks/queries/use-volumes'
export { useDomains, useDomain, domainKeys } from '@/hooks/queries/use-domains'
export { useSSHKeys, useSSHKey, sshKeyKeys } from '@/hooks/queries/use-ssh-keys'
export { usePrograms, useProgram, programKeys } from '@/hooks/queries/use-programs'
export { useWebsites, useWebsite, websiteKeys } from '@/hooks/queries/use-websites'
